db_dir:     'db/'
config_dir: 'config/'
sqlite_db:  'db/main.db'
nmap_db:    'db/nmap/'
dnsenum_db: 'db/dnsenum/'
masscan_db: 'db/masscan/'
whatweb_db: 'db/whatweb/'
nmap_path:    '/usr/bin/env nmap'
dnsenum_path: '/usr/bin/env dnsenum'
masscan_path: '/usr/bin/env masscan'
whatweb_path: '/usr/bin/env whatweb'
nmap_args:    '-Pn '
dnsenum_args: '--nocolor --private --noreverse --threads 64'
masscan_args: '--rate=10000'
whatweb_args: '--no-errors -t 255'
